### ISSUE TITLE
[Feature Request] Send Picture at the end of any Print

### ISSUE THREAD

**Issue by SebiWolze** [DanJunior78/Repetier-Server-Telegram-Bot#5]
Hi DanJunior78,

thanks for your Bot, tried V4, works perfect on my PI4.
As I moved from Octoprint to Repetier Server, I am still missing the function "Picture at the End of the Print".
Its very nice to get a picture of the finished print, maybe its possible to generate a small delay of approx. 30 seconds after the printer reports he finished. 
So the Printbed and Extruder has time to drive home.

Thanks again.

Sebi

**Comment by DanJunior78** [comment]
Hello Sebastian, i´ll plan it for the next version. Best would be to be able to choose any of the formats which are included (video, gif or png) and to choose a delay time. 
regards

**Comment by SebiWolze** [comment]
Sounds great, yes!
Really great job!

**Comment by DanJunior78** [comment]
Impemented in the latest version. The next update will implement a bigger modification in the application core. I´ve several times killed the connection to telegram by the amount of data exchange of the bot to telegram, lol. 
This is the reason i´ve removed the "messages" which have been buggy in V4.01, but was stable on my further tests, after some bugfixing. But i couldn´t prevent to exceed the limitation of Telegram. So...some homework to do here from my side.
Please feel free to test the actual version. If it´s working for you. The pictures text isn´t nice. Will be fixed in the next version too.
Stay tuned.

**Comment by DanJunior78** [comment]
Please reopen if there is a problem.
